### ISSUE TITLE
Unable to boot VMs wih Leap 15.0 dracut

### ISSUE THREAD

**Issue by morbidrsa** [rapido-linux/rapido#42] opened 2018-04-24 13:40 UTC
When using rapido on openSUSE Leap 15.0, I can't boot up the VMs but get stuck after multi-user.target

Welcome to openSUSE Leap 15.0 Beta dracut-044-29.1 (Initramfs)!

[    0.383121] systemd[1]: No hostname configured.
[    0.383743] systemd[1]: Set hostname to <localhost>.
[    0.384377] systemd[1]: Initializing machine ID from random generator.
[    0.394213] systemd[1]: Listening on udev Kernel Socket.
[  OK  ] Listening on udev Kernel Socket.
[    0.395758] systemd[1]: Listening on udev Control Socket.
[  OK  ] Listening on udev Control Socket.
[    0.397718] systemd[1]: Reached target Swap.
[  OK  ] Reached target Swap.
[  OK  ] Created slice System Slice.
[  OK  ] Reached target Slices.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Reached target Local File Systems.
[  OK  ] Listening on Journal Socket.
         Starting udev Coldplug all Devices...
[  OK  ] Reached target Sockets.
         Starting Create list of required st…ce nodes for the current kernel...
         Starting Journal Service...
         Starting Load Kernel Modules...
[  OK  ] Reached target Timers.
[  OK  ] Started Create list of required sta…vice nodes for the current kernel.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Started Journal Service.
[FAILED] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details.
[  OK  ] Started Create Static Device Nodes in /dev.
         Starting udev Kernel Device Manager...
         Starting Apply Kernel Variables...
[  OK  ] Started Apply Kernel Variables.
[  OK  ] Started udev Kernel Device Manager.
         Mounting Kernel Configuration File System...
[  OK  ] Mounted Kernel Configuration File System.
[  OK  ] Started udev Coldplug all Devices.
[  OK  ] Reached target System Initialization.
[  OK  ] Reached target Basic System.
[  OK  ] Reached target Multi-User System.
[    1.331688] tsc: Refined TSC clocksource calibration: 2594.085 MHz
[    1.334155] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x25646885a38, max_idle_ns: 440795311131 s
[    1.338581] clocksource: Switched to clocksource tsc

**Comment by ddiss** [comment] 2018-05-02 08:38
Strange, I haven't seen this on SLE15.
Which kernel, .config and cut script are you using?

**Comment by morbidrsa** [comment] 2018-05-02 11:41
Kernel is upstream master (daily git pulls). config ist kernel/vanilla_config from the rapido tree. Qemu qemu-2.11.1-lp150.4.3.x86_64 and dracut dracut-044.1-29.1.x86_64

**Comment by ddiss** [comment] 2018-05-02 11:42
Thanks. I'll see whether I can reproduce this.

**Comment by ddiss** [comment] 2018-05-03 17:31
I did some testing on Leap 15 with dracut-044.1-lp150.13.1 and qemu-2.11.1-lp150.5.1 (with KVM disabled due to the bios of the machine I was using).

A simple minimal VM (https://github.com/ddiss/rapido/tree/simple_example) booted fine.
One thing I did notice was that mkfs.xfs stalls in the getrandom() syscall code path. I've not yet found out whether this is due to a kernel issue or otherwise.

I also noticed that your output above is using sytemd. Can you confirm that your cut script specifies  '--modules "... systemd systemd-initrd dracut-systemd..."' ? My guess is that you're using systemd without the "dracut-systemd" module.

**Comment by morbidrsa** [comment] 2018-05-04 08:08
> I also noticed that your output above is using sytemd. Can you confirm that your cut script specifies '--modules "... systemd systemd-initrd dracut-systemd..."' ? My guess is that you're using systemd without the "dracut-systemd" module.

Nope and adding it to cut_blktests_local.sh fixes it. Thanks for the hint.

The next question is, shall we add it to all cut_* scripts?

**Comment by ddiss** [comment] 2018-05-04 09:01
> Nope and adding it to cut_blktests_local.sh fixes it. Thanks for the hint.
> 
> The next question is, shall we add it to all cut_* scripts?

I don't think so - AFAIK it's only needed if the "systemd" Dracut module is added without the corresponding "dracut-systemd" module.
Most Cut scripts don't have a systemd dependency. I don't see cut_blktests_local.sh upstream, but blktests_zram works fine without systemd.

**Comment by ddiss** [comment] 2018-05-04 11:14
Closing... Please feel free to reopen if you encounter further issues.

**Closed by ddiss** 2018-05-04 11:14 UTC

**Comment by ddiss** [comment] 2018-05-11 14:42
> One thing I did notice was that mkfs.xfs stalls in the getrandom() syscall code path. I've not yet found out whether this is due to a kernel issue or otherwise.

For posterity - this kernel issue is tracked at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897572

**Comment by morbidrsa** [comment] 2018-05-11 15:14
Thanks for the update.
