### ISSUE TITLE
Use common set of applications/libraries in cut_* scripts

### ISSUE THREAD

**Issue by luis-henrix** [rapido-linux/rapido#18] opened 2017-05-31 13:27 UTC
Instead of duplicating a huge amount of applications in the 'dracut --install' (e.g. ps, rmdir, resize, dd, ...), each cut_ script could simply add those applications/libs/... that would be required for that specific script.
In the long run, I guess a single cut_ script would be required and different configuration files would simply set specific sets of applications, libs, kernel modules, ...

**Comment by ddiss** [comment] 2017-05-31 14:46
This looks like a duplicate of https://github.com/rapido-linux/rapido/issues/2 , or am I missing something?

**Comment by ddiss** [comment] 2018-11-26 15:11
I'd prefer to avoid adding further abstractions in front of Dracut here, to ensure that cut scripts remain as simple as possible.

FWIW, I've implemented a more pluggable and maintainable architecture in golang as part of Rapidos (https://gitlab.com/rapidos/rapidos) . Instead of Dracut, Rapidos uses u-root image generation which includes a minimal user-space written in pure go.

**Closed by ddiss** 2018-11-26 15:11 UTC
